// Generated by Spacedrive using Specta - DO NOT EDIT
// See core/src/bin/generate_swift_types.rs

import Foundation

extension Device: CacheableResource {
    public static var resourceType: String { "device" }
}

extension File: CacheableResource {
    public static var resourceType: String { "file" }
}

extension Library: CacheableResource {
    public static var resourceType: String { "library" }
}

extension Location: CacheableResource {
    public static var resourceType: String { "location" }
}

extension Space: CacheableResource {
    public static var resourceType: String { "space" }
}

extension SpaceGroup: CacheableResource {
    public static var resourceType: String { "space_group" }
}

extension SpaceItem: CacheableResource {
    public static var resourceType: String { "space_item" }
}

extension SpaceLayout: CacheableResource {
    public static var resourceType: String { "space_layout" }
}

extension Tag: CacheableResource {
    public static var resourceType: String { "tag" }
}

extension Volume: CacheableResource {
    public static var resourceType: String { "volume" }
}

public enum GeneratedResources {
    /// All resource type identifiers known to this build of the core.
    public static let allResourceTypes: [String] = [
        "device",
        "file",
        "library",
        "location",
        "space",
        "space_group",
        "space_item",
        "space_layout",
        "tag",
        "volume",
    ]

    /// Register every generated resource type with a registry.
    /// The shared registry calls this automatically on first access.
    public static func registerAll(into registry: ResourceTypeRegistry = .shared) {
        registry.register(Device.self)
        registry.register(File.self)
        registry.register(Library.self)
        registry.register(Location.self)
        registry.register(Space.self)
        registry.register(SpaceGroup.self)
        registry.register(SpaceItem.self)
        registry.register(SpaceLayout.self)
        registry.register(Tag.self)
        registry.register(Volume.self)
    }
}
